services:

  db:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: flask_app
      MYSQL_ROOT_PASSWORD: a1s2d3f4
      MYSQL_ROOT_HOST: db
      MYSQL_PASSWORD: a1s2d3f4

    volumes:
      - ./mysql_local.cnf:/etc/mysql/conf.d/mysql_local.cnf:ro

  web:
    container_name: web
    build: .
    entrypoint: ./bin/webapp.sh
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - CeleryScheduler
      - db

  redis:
    image: redis
    container_name: redis
    volumes:
      - .:/app

  celery:
    image: celery:3.1
    container_name: celery
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ./bin/celery.sh
    links:
      - redis

  CeleryScheduler:
    image: celery:3.1
    build: .
    entrypoint: ./bin/celery-scheduler.sh
    container_name: celery-schedule
    restart: unless-stopped
    volumes:
      - .:/app

    links:
      - redis
