"""Second_Migration

Revision ID: bc50ad6503c8
Revises: 5ad0c6d5d9d5
Create Date: 2023-01-10 05:24:50.107397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc50ad6503c8'
down_revision = '5ad0c6d5d9d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=28), nullable=False),
    sa.Column('created_at', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=28), nullable=False),
    sa.Column('password', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('car')
    # ### end Alembic commands ###
